const mongoose = require('mongoose');

const ZerodhaOrderSchema = new mongoose.Schema({
  account_id: { type: String, required: true },
  placed_by: { type: String, required: true },
  order_id: { type: String, required: true, unique: true },
  exchange_order_id: { type: String },
  parent_order_id: { type: String },
  status: { type: String, required: true },
  status_message: { type: String },
  status_message_raw: { type: String },
  order_timestamp: { type: Date, required: true },
  exchange_update_timestamp: { type: Date },
  exchange_timestamp: { type: Date },
  variety: { type: String, required: true },
  modified: { type: Boolean, required: true },
  exchange: { type: String, required: true },
  tradingsymbol: { type: String, required: true },
  instrument_token: { type: Number, required: true },
  order_type: { type: String, required: true },
  transaction_type: { type: String, required: true },
  validity: { type: String, required: true },
  validity_ttl: { type: Number },
  product: { type: String, required: true },
  quantity: { type: Number, required: true },
  disclosed_quantity: { type: Number },
  price: { type: Number },
  trigger_price: { type: Number },
  average_price: { type: Number },
  filled_quantity: { type: Number, required: true },
  pending_quantity: { type: Number },
  cancelled_quantity: { type: Number },
  market_protection: { type: Number },
  meta: { type: Object },
  tag: { type: String },
  guid: { type: String },
});

module.exports = mongoose.model('ZerodhaOrder', ZerodhaOrderSchema);
